name: remote ssh command
on: [push]
jobs:
  build:
    name: Whoami
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.LIPSUMAR_IO_HOST }}
          username: ${{ secrets.LIPSUMAR_IO_USER }}
          key: ${{ secrets.LIPSUMAR_IO_KEY }}
          script: cd ai-bingo && git pull && docker-compose build && docker-compose up -d
